//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klassenliste
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKlassenliste : DbContext
    {
        public DBKlassenliste()
            : base("name=KlassenlisteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klasse> Klasse { get; set; }
        public virtual DbSet<Kurs> Kurs { get; set; }
        public virtual DbSet<Teilnehmer> Teilnehmer { get; set; }
        public virtual DbSet<Teilnehmer_has_Kurs> Teilnehmer_has_Kurs { get; set; }
    }
}
