//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klassenliste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klasse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klasse()
        {
            this.Teilnehmer = new HashSet<Teilnehmer>();
        }
    
        public int IdKlasse { get; set; }
        public string Bezeichnung { get; set; }
        public string Kuerzel { get; set; }
        public Nullable<int> Jahr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teilnehmer> Teilnehmer { get; set; }

        public override string ToString()
        {
            return Bezeichnung;
        }
    }
}
