//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klassenliste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teilnehmer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teilnehmer()
        {
            this.Teilnehmer_has_Kurs = new HashSet<Teilnehmer_has_Kurs>();
        }
    
        public int IdTeilnehmer { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public int Klasse_IdKlasse { get; set; }
    
        public virtual Klasse Klasse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teilnehmer_has_Kurs> Teilnehmer_has_Kurs { get; set; }
    }
}
